<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/13
 * Time: 17:08
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array(
    'log_id' =>
        array (
            'field' => 'log_id',
            'label' => 'ID',
            'pk' => true,
            'add' => false,
            'edit' => false,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'hongbao_id'=>array(
        'field' => 'hongbao_id',
        'label' => '红包ID',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'min_amount'=>array(
        'field' => 'min_amount',
        'label' => '红包金额',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'amount'=>array(
        'field' => 'hongbao_amount',
        'label' => '红包金额',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'uid'=>array(
        'field' => 'uid',
        'label' => '用户id',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'day'=>array(
        'field' => 'day',
        'label' => '领取天数',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'clientip'=>array(
        'field' => 'clientip',
        'label' => 'ip',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'dateline'=>array(
        'field' => 'dateline',
        'label' => '创建时间',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'dateline',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),'type'=>array(
        'field' => 'type',
        'label' => '类型',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    )
);