<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/26
 * Time: 13:42
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
//log_id,bills_id,amount,jifen,uid,bills_sn,dateline
return array(
    'log_id'=>array(
            'field' => 'log_id',
            'label' => 'log_id',
            'pk' => true,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '',
            'default' => '',
            'SO' => '',
    ),
    'bills_id'=>array(
        'field' => 'bills_id',
        'label' => '对账单id ',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'fee'=>array(
        'field' => 'fee',
        'label' => '金额 ',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => ' number',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'jifen'=>array(
        'field' => 'jifen',
        'label' => '积分 ',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => ' number',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'uid'=>array(
        'field' => 'uid',
        'label' => '用户id ',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'bills_sn'=>array(
        'field' => 'bills_sn',
        'label' => '日期 ',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'dateline'=>array(
        'field' => 'dateline',
        'label' => '创建时间 ',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'order_id'=>array(
        'field' => 'order_id',
        'label' => '订单id',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    )

);