<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
//order_id,from,o_lng,o_lat,lng,lat,o_addr,addr,amount,tip,product,dateline,contact,mobile,o_mobile,o_contact,yuji_price

return array (
  'order_id' => 
  array (
    'field' => 'order_id',
    'label' => '订单ID',
    'pk' => true,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单ID',
    'default' => '',
    'SO' => false,
  ),
  'from'=>array(
      'field' => 'from',
      'label' => '订单类型',
      'pk' => false,
      'add' => true,
      'edit' => true,
      'html' => false,
      'empty' => false,
      'show' => true,
      'list' => true,
      'type' => 'text',
      'comment' => '订单类型',
      'default' => '',
      'SO' => false,
  ),
    'o_lng'=>array(
        'field' => 'o_lng',
        'label' => '经度',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '经度',
        'default' => '',
        'SO' => false,
    ),
   'o_lat'=>array(
    'field' => 'o_lat',
    'label' => '维度',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '维度',
    'default' => '',
    'SO' => false,
  ),
    'lng'=>array(
        'field' => 'lng',
        'label' => '经度',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '经度',
        'default' => '',
        'SO' => false,
    )
   ,
    'lat'=>array(
        'field' => 'lat',
        'label' => '维度',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '维度',
        'default' => '',
        'SO' => false,
    ),
    'o_addr'=>array(
    'field' => 'o_addr',
    'label' => '收货地址',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '收货地址',
    'default' => '',
    'SO' => false,
   ),
    'addr'=>array(
        'field' => 'addr',
        'label' => '收货地址',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '收货地址',
        'default' => '',
        'SO' => false,
    ),
    'amount'=>array(
        'field' => 'amount',
        'label' => '配送费',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '配送费',
        'default' => '',
        'SO' => false,
    ),
    'tip'=>array(
        'field' => 'tip',
        'label' => '小费',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '配送费',
        'default' => '',
        'SO' => false,
    ),
    'product'=>array(
        'field' => 'product',
        'label' => '商品',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '商品',
        'default' => '',
        'SO' => false,
    ),
    'dateline'=>array(
        'field' => 'dateline',
        'label' => '创建时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'dateline',
        'comment' => '创建时间',
        'default' => '',
        'SO' => false,
    ),
    'contact'=>array(
        'field' => 'contact',
        'label' => '联系人',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '联系人',
        'default' => '',
        'SO' => false,
    ),
    'mobile'=>array(
        'field' => 'mobile',
        'label' => '手机',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '手机',
        'default' => '',
        'SO' => false,
    )
    ,'o_mobile'=>array(
        'field' => 'o_mobile',
        'label' => '手机',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '手机',
        'default' => '',
        'SO' => false,
    ),
    'o_contact'=>array(
        'field' => 'o_contact',
        'label' => '联系人',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '联系人',
        'default' => '',
        'SO' => false,
    ),
    'yuji_price'=>array(
        'field' => 'yuji_price',
        'label' => '预计价格',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '预计价格',
        'default' => '',
        'SO' => false,
    ),
    'price'=>array(
        'field' => 'price',
        'label' => '物品价值',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '物品价值',
        'default' => '',
        'SO' => false,
    ),
    'weight'=>array(
        'field' => 'weight',
        'label' => '物品重量',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '物品重量',
        'default' => '',
        'SO' => false,
    ),
    'type'=>array(
        'field' => 'type',
        'label' => '订单类别',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '订单类别',
        'default' => '',
        'SO' => false,
    ),
    'ext_shop_id'=>array(
        'field' => 'ext_shop_id',
        'label' => '商城订单商家id',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '商城订单商家id',
        'default' => '',
        'SO' => false,
    ),
    'extend'=>array(
        'field' => 'extend',
        'label' => '商家信息冗余',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '商家信息冗余',
        'default' => '',
        'SO' => false,
    )
);