<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'qiang_id' => 
  array (
    'field' => 'qiang_id',
    'label' => '抢购ID',
    'pk' => true,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'shop_id' => 
  array (
    'field' => 'shop_id',
    'label' => '商户ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商户ID',
    'default' => '',
    'SO' => '=',
  ),
  'city_id' =>
  array (
    'field' => 'city_id',
    'label' => '城市ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '城市ID',
    'default' => '',
    'SO' => false,
  ),
    'business_id' =>
  array (
    'field' => 'business_id',
    'label' => '商户所属的商圈ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商户所属的商圈ID',
    'default' => '',
    'SO' => false,
  ),
  'area_id' =>
  array (
    'field' => 'area_id',
    'label' => '区县ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '区县ID',
    'default' => '',
    'SO' => false,
  ),
  'title' => 
  array (
    'field' => 'title',
    'label' => '名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '',
    'default' => '',
    'SO' => 'like',
  ),
  'photo' => 
  array (
    'field' => 'photo',
    'label' => '图片',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'photo',
    'comment' => '图片',
    'default' => '',
    'SO' => false,
  ),
  'price' => 
  array (
    'field' => 'price',
    'label' => '原价',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '原价',
    'default' => '',
    'SO' => '=',
  ),
  'discount_price' => 
  array (
    'field' => 'discount_price',
    'label' => '折扣价',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '折扣价',
    'default' => '',
    'SO' => '=',
  ),
  'type' =>
array(
    'field'   => 'type',
    'label'   => '抢购类型',
    'pk'      => false,
    'add'     => true,
    'edit'    => true,
    'html'    => false, 
    'empty'   => false,
    'show'    => true,
    'list'    => true,
    'type'    => 'text',
    'comment' => '抢购类型： goods:实物,ticket:电子券',
    'default' => 'ticket',
    'SO'      => '=',
),
  'freight' => 
  array (
    'field' => 'freight',
    'label' => '运费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '运费',
    'default' => '',
    'SO' => '=',
  ),
    'is_tui' => 
  array (
    'field' => 'is_tui',
    'label' => '退款状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '0:不支持,1:支持',
    'default' => '1',
    'SO' => false,
  ),
    'pei_type' => 
  array (
    'field' => 'pei_type',
    'label' => '消费类型',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '0:物流配送,1:到店消费，2:全部支持',
    'default' => '0',
    'SO' => false,
  ),
    'is_yuyue' => 
  array (
    'field' => 'is_yuyue',
    'label' => '预约状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '0:免预约,1:提前预约',
    'default' => '0',
    'SO' => false,
  ),
    'is_limit' => 
  array (
    'field' => 'is_limit',
    'label' => '限购状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '0:不限购,1:限购',
    'default' => '0',
    'SO' => false,
  ),
    'limit_sku' => 
  array (
    'field' => 'limit_sku',
    'label' => '每单限购数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '每单限购数',
    'default' => '',
    'SO' => 'between',
  ),
  'sku' => 
  array (
    'field' => 'sku',
    'label' => '库存数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '库存数',
    'default' => '',
    'SO' => 'between',
  ),
  'count_sku' => 
  array (
    'field' => 'count_sku',
    'label' => '总库存数',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '总库存数',
    'default' => '',
    'SO' => 'between',
  ),
    'sales' => 
  array (
    'field' => 'sales',
    'label' => '销量',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '销量',
    'default' => '',
    'SO' => 'between',
  ),
    'is_onsale' => 
  array (
    'field' => 'is_onsale',
    'label' => '上架状态',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '0:上架,1:下架',
    'default' => '0',
    'SO' => false,
  ),
  'qiang_ltime'=>array(
        'field' => 'qiang_ltime',
        'label' => '抢购截止时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,

    ),
    'use_ltime'=>array(
        'field' => 'use_ltime',
        'label' => '消费截止时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
  'info' => 
  array (
    'field' => 'info',
    'label' => '商品详情',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'editor',
    'comment' => '商品详情',
    'default' => '',
    'SO' => false,
  ),
  'rules' => 
  array (
    'field' => 'rules',
    'label' => '规则',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'editor',
    'comment' => '规则',
    'default' => '',
    'SO' => false,
  ),
  'orderby' => 
  array (
    'field' => 'orderby',
    'label' => '排序',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '排序',
    'default' => '50',
    'SO' => '=',
  ),
  'closed' => 
  array (
    'field' => 'closed',
    'label' => '删除标识',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '',
    'default' => '',
    'SO' => '=',
  ),
  'clientip' => 
  array (
    'field' => 'clientip',
    'label' => '创建IP',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'ip',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'dateline' => 
  array (
    'field' => 'dateline',
    'label' => '添加时间',
    'pk' => false,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'dateline',
    'comment' => '',
    'default' => '',
    'SO' => false,
  ),
  'bl'=>array(
        'field' => 'bl',
        'label' => '抽佣比例',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => 'bl',
        'default' => '',
        'SO' => 'false',
    )
);