<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006115343.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006115343.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1046";
$z[1][4]['height']="800";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006115345.jpg ",241,387);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006115345.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1519";
$z[2][4]['height']="750";
$z[3]=Array("img"," /uploads/allimg/171006/1-1G006115346.jpg ",389,536);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171006/1-1G006115346.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1500";
$z[3][4]['height']="1136";
$z[4]=Array("img"," /uploads/allimg/171006/1-1G006115348.jpg ",538,685);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/171006/1-1G006115348.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1500";
$z[4][4]['height']="1110";

?>