<?php
$z[0]=Array("field","",14,42);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",69,95);
$z[1][4]=array();
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",97,126);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("php"," AddFilter(2,1,'jz');",411,453);
$z[3][4]=array();
$z[4]=Array("php"," AddFilter(2,1,'fg');",727,769);
$z[4][4]=array();
$z[5]=Array("php"," AddFilter(2,1,'hx');",1043,1085);
$z[5][4]=array();
$z[6]=Array("php"," AddFilter(2,1,'mj');",1358,1400);
$z[6][4]=array();

?>