{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/171006/1-1G006153A4.jpg' text='' width='2400' height='1700'} /uploads/allimg/171006/1-1G006153A4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006153A7.jpg' text='' width='2400' height='1790'} /uploads/allimg/171006/1-1G006153A7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006153F0.jpg' text='' width='2598' height='2650'} /uploads/allimg/171006/1-1G006153F0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006153F5.jpg' text='' width='3390' height='2363'} /uploads/allimg/171006/1-1G006153F5.jpg {/dede:img}
