
<field:hx itemname="房屋户型" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:hx>

<field:mj itemname="房屋面积" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mj>

<field:xq itemname="小区名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xq>

<field:ch itemname="客户称呼" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ch>

<field:tel itemname="客户电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:fg itemname="装修风格" autofield="1" type="select" isnull="true" default="现代,美式,简欧,中式,欧式,田园,新古典,地中海,北欧,后现代,日式,复古,混搭"  maxlength="250" page="">
</field:fg>

