<li>
      <div class="building-img fl"> <a href="view.php?aid=[field:id/]"> <img class="lazy" src="/m/skin/images/blank.gif" data-echo="[field:picname/]" alt="[field:title/]"> </a> </div>
      <div class="building-info fl">
        <div class="building-ti"> <a href="view.php?aid=[field:id/]">[field:title/]</a> </div>
        <div class="building-step"> <em></em>
          <div class="building-step-box">
            <div class="building-step-bar" style="width: 100%;"> <span>[field:c_sjs/]</span> </div>
          </div>
          <em></em> </div>
        <p>房屋信息：[field:house_info/]</p>
        <p>总价：[field:total_price/]</p>
      </div>
    </li>