<?php
$z[0]=Array("arcurl","",121,136);
$z[0][4]=array();
$z[1]=Array("litpic","",148,163);
$z[1][4]=array();
$z[2]=Array("title","",193,207);
$z[2][4]=array();
$z[3]=Array("title","",237,251);
$z[3][4]=array();
$z[4]=Array("shorttitle","",270,289);
$z[4][4]=array();
$z[5]=Array("description","",369,419);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,300)";
$z[6]=Array("title","",504,518);
$z[6][4]=array();

?>