<div class="work-man-box">
        <div class="work-man-info clearfix">
          <div class="work-man-img fl"> <a href="[field:arcurl/]"><img src="[field:litpic/]" width="80" height="80" alt="[field:title/]" /></a> </div>
          <h3>[field:title/]</h3>
          <p>[field:shorttitle/]</p>
        </div>
        <div class="work-tips">
          <p>设计理念：[field:description function="cn_substr(@me,300)"/]...</p>
        </div>
      </div>
      <a href="javascript:;" class="adiw" title="[field:title/]" cid="893" yuyue="">预约TA为我设计</a> </div>