<li>
        <div class="show-img"> <a href="[field:id runphp='yes'] $id=@me;@me='';$url=GetOneArchive($id);@me=$url['arcurl'];[/field:id]"> <img class="lazy" src="[field:litpic/]" width="380" height="245" alt="[field:title/]" /> </a> </div>
        <div class="show-info2">
          <h4 class="alb-title"><a href="[field:id runphp='yes'] $id=@me;@me='';$url=GetOneArchive($id);@me=$url['arcurl'];[/field:id]">[field:title/]</a></h4>
        </div>
      </li>