<?php
$z[0]=Array("id"," \$id=@me;@me='';\$url=GetOneArchive(\$id);@me=\$url['arcurl'];",45,138);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",164,179);
$z[1][4]=array();
$z[2]=Array("title","",211,225);
$z[2][4]=array();
$z[3]=Array("id"," \$id=@me;@me='';\$url=GetOneArchive(\$id);@me=\$url['arcurl'];",316,409);
$z[3][4]=array();
$z[3][4]['runphp']="yes";
$z[4]=Array("title","",411,425);
$z[4][4]=array();

?>