<?php
$z[0]=Array("field","",29,57);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",84,110);
$z[1][4]=array();
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",112,141);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("php"," AddFilter(2,1,'fg');",427,469);
$z[3][4]=array();
$z[4]=Array("php"," AddFilter(2,1,'hx');",744,786);
$z[4][4]=array();
$z[5]=Array("php"," AddFilter(2,1,'mj');",1060,1102);
$z[5][4]=array();

?>