<li>
        <div class="show-img"> <a href="[field:arcurl/]"> <img class="lazy" src="[field:picname/]" width="380" height="245" alt="[field:title/]" /> </a>
          <div class="show-tips">
            <p>户型：[field:hx/]</p>
            <p>面积：[field:anmj/]</p>
            <p>预算：[field:zj/]</p>
            <p><span>[field:fg/]</span></p>
          </div>
        </div>
        <div class="show-info">
          <h4 class="alb-title"><a href="[field:arcurl/]">[field:title/]</a></h4>
          <div class="alb-bt" ><span class="fl"><img src="[field:writer/]" alt="[field:writer/]" />
            <p>[field:sjs/]</p>
            </span> <a class="fr" href="http://wpa.qq.com/msgrd?v=3&site=[field:global.cfg_webname/]&menu=yes&uin=[field:global.cfg_kfqq/]" title="[field:sjs/]" yuyue='' >预约设计</a> </div>
        </div>
      </li>