<div class="designer-index">
  <div class="designer-con">
    <div class="designer-con-1">
      <div class="design-content">
        <div class="team clearfix"> {dede:arclist limit='0,1' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-star team-box fl" style="margin:0;">
            <div class="team-img fl pick-down"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-star-info fl">
              <h3>[field:title/]<em>[field:d_zw/]</em></h3>
              <span></span>
              <p>设计理念：[field:description/]</p>
            </div>
          </div>
          {/dede:arclist}
          {dede:arclist limit='1,2' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl" >
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"> <b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist} </div>
      </div>
      <div class="design-content">
        <div class="team clearfix"> {dede:arclist limit='3,1' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl" style="margin:0;">
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist}
          {dede:arclist limit='4,3' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl" >
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist} </div>
      </div>
    </div>
    <div class="designer-con-2 dn">
      <div class="design-content">
        <div class="team clearfix"> {dede:arclist limit='7,1' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"   style="margin:0;">
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist}  
          {dede:arclist limit='8,3' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"  >
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist} </div>
      </div>
      <div class="design-content">
        <div class="team clearfix"> {dede:arclist limit='11,1' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"   style="margin:0;">
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist}
          {dede:arclist limit='12,3' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"  >
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist} </div>
      </div>
    </div>
    <div class="designer-con-3 dn">
      <div class="design-content">
        <div class="team clearfix"> {dede:arclist limit='15,1' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"   style="margin:0;">
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist}
          {dede:arclist limit='16,3' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"  >
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist} </div>
      </div>
      <div class="design-content">
        <div class="team clearfix"> {dede:arclist limit='19,1' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"   style="margin:0;">
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist}
          {dede:arclist limit='20,3' orderby ='pubdate' channelid='17' addfields='d_zw'  }
          <div class="team-box fl"  >
            <div class="team-img"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-info"><b>[field:title/]</b> <em>[field:d_zw/]</em> </div>
          </div>
          {/dede:arclist} </div>
      </div>
    </div>
  </div>
  <div class="designer-pick">
    <ul>
      <li aa="1" class="active"></li>
      <li aa="2"></li>
      <li aa="3"></li>
    </ul>
  </div>
</div>