
<field:mz itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mz>

<field:sjhm itemname="手机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sjhm>

<field:lp itemname="楼盘" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lp>

<field:mmjj itemname="面积" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mmjj>
