<?php
$z[0]=Array("global","\n            \$a=\"class='mro'\";\n            \$b=\"\";\n            if ((@me%4)==0 && @me!=30) @me=\$a;\n            else  @me=\$b;\n            ",4,196);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",213,228);
$z[1][4]=array();
$z[2]=Array("picname","",241,257);
$z[2][4]=array();
$z[3]=Array("picname","",283,299);
$z[3][4]=array();
$z[4]=Array("title","",306,320);
$z[4][4]=array();
$z[5]=Array("title","",352,366);
$z[5][4]=array();
$z[6]=Array("title","",434,448);
$z[6][4]=array();
$z[7]=Array("click","",475,489);
$z[7][4]=array();

?>