<li>
            <div class="notice-img fl"> <a href="[field:arcurl/]"> <img class="lazy" src="[field:picname/]" data-echo="[field:picname/]" width="298" height="198" alt="[field:title/]" /> </a> </div>
            <div class="notice-info fr">
              <div class="notice-ti">
                <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                <p>[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
              </div>
              <div class="notice-word">
                <p>[field:description function="cn_substr(@me,320)"/]...</p>
              </div>
            </div>
          </li>