<li>
        <div class="building-img fl"> <a href="[field:arcurl/]"> <img class="lazy" src="[field:picname/]" data-echo="[field:picname/]" alt="[field:title/]" /> </a> </div>
        <div class="building-info fl">
          <div class="building-ti"> <a href="[field:arcurl/]">[field:title/]</a> </div>
          <div class="building-con">
            <p>工程进度：[field:c_content/]</p>
            <p>房屋信息：[field:house_info/]</p>
            <p>工程造价：[field:total_price/]</p>
          </div>
          <a href="[field:arcurl/]" class="building-btn">查看详情</a> </div>
      </li>