<?php
$z[0]=Array("field","",98,127);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n        <li>\r\n          <div class=\"news-time\"> <em>[field:pubdate function=\"MyDate('m-d',@me)\"/]</em> <span>[field:pubdate function=\"MyDate('Y',@me)\"/]</span> </div>\r\n          <div class=\"news-ti\"> <a href=\"[field:arcurl/]\">[field:title/]</a> </div>\r\n          <div class=\"news-con\">\r\n            <p>[field:description function=\"cn_substr(@me,120)\"/]...</p>\r\n          </div>\r\n        </li>\r\n        ",212,684);
$z[1][4]=array();
$z[1][4]['titlelen']="80";
$z[1][4]['orderby']="pubdate";
$z[1][4]['row']="3";
$z[2]=Array("field","",747,775);
$z[2][4]=array();
$z[2][4]['name']="typeurl";

?>