<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006114109.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006114109.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1280";
$z[1][4]['height']="960";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006114116.jpg ",241,387);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006114116.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1280";
$z[2][4]['height']="960";
$z[3]=Array("img"," /uploads/allimg/171006/1-1G006114157.jpg ",389,536);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171006/1-1G006114157.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="4000";
$z[3][4]['height']="2828";

?>