{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/171006/1-1G006113U8.jpg' text='' width='1500' height='1056'} /uploads/allimg/171006/1-1G006113U8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006113Z0.jpg' text='' width='1500' height='953'} /uploads/allimg/171006/1-1G006113Z0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006113Z2.jpg' text='' width='1500' height='924'} /uploads/allimg/171006/1-1G006113Z2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006113Z5.jpg' text='' width='1500' height='1056'} /uploads/allimg/171006/1-1G006113Z5.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006113910.jpg' text='' width='1501' height='1125'} /uploads/allimg/171006/1-1G006113910.jpg {/dede:img}
