<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006124I3.jpg ",93,236);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006124I3.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="992";
$z[1][4]['height']="764";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006124I4.jpg ",238,381);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006124I4.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="947";
$z[2][4]['height']="754";

?>