<?php
$z[0]=Array("field","",95,124);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n      <li [field:global runphp='yes' name=autoindex]\n            \$a=\"class='mro'\";\n            \$b=\"\";\n            if ((@me%4)==0 && @me!=30) @me=\$a;\n            else  @me=\$b;\n            [/field:global]>\n      <a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" class=\"lazy\" data-echo=\"[field:picname/]\" alt=\"[field:title/]\">\n      <div class=\"ifsb-show\">[field:title/]</div>\n      <div class=\"ifsb-hide\" style=\"top: 351px;\">\n        <p>[field:title/]</p>\n        <b></b> <span>[field:click/]人已浏览</span> <i>立即查看</i> </div>\n      </a>\n      </li>\n      ",174,814);
$z[1][4]=array();
$z[1][4]['titlelen']="80";
$z[1][4]['orderby']="pubdate";
$z[1][4]['row']="7";

?>