<?php
$z[0]=Array("global","\r\n            \$a=\"class='mro'\";\r\n            \$b=\"\";\r\n            if ((@me%4)==0 && @me!=30) @me=\$a;\r\n            else  @me=\$b;\r\n            ",4,201);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",219,234);
$z[1][4]=array();
$z[2]=Array("picname","",247,263);
$z[2][4]=array();
$z[3]=Array("picname","",289,305);
$z[3][4]=array();
$z[4]=Array("title","",312,326);
$z[4][4]=array();
$z[5]=Array("title","",359,373);
$z[5][4]=array();
$z[6]=Array("title","",443,457);
$z[6][4]=array();
$z[7]=Array("click","",485,499);
$z[7][4]=array();

?>