<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006105314.jpg ",93,240);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006105314.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1162";
$z[1][4]['height']="1200";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006105333.jpg ",242,388);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006105333.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="902";
$z[2][4]['height']="1107";
$z[3]=Array("img"," /uploads/allimg/171006/1-1G006105335.jpg ",390,537);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171006/1-1G006105335.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1918";
$z[3][4]['height']="1240";
$z[4]=Array("img"," /uploads/allimg/171006/1-1G006105337.jpg ",539,686);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/171006/1-1G006105337.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1227";
$z[4][4]['height']="1200";

?>