<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006135446.jpg ",93,240);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006135446.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1500";
$z[1][4]['height']="1095";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006135452.jpg ",242,389);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006135452.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1500";
$z[2][4]['height']="1098";
$z[3]=Array("img"," /uploads/allimg/171006/1-1G006135453.jpg ",391,538);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171006/1-1G006135453.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1500";
$z[3][4]['height']="1094";
$z[4]=Array("img"," /uploads/allimg/171006/1-1G006135456.jpg ",540,687);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/171006/1-1G006135456.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="4842";
$z[4][4]['height']="3390";

?>