<?php
$z[0]=Array("field","",98,127);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n      <li [field:global runphp='yes' name=autoindex]\r\n            \$a=\"class='mro'\";\r\n            \$b=\"\";\r\n            if ((@me%4)==0 && @me!=30) @me=\$a;\r\n            else  @me=\$b;\r\n            [/field:global]>\r\n      <a href=\"[field:arcurl/]\"> <img src=\".[field:picname/]\" class=\"lazy\" data-echo=\"[field:picname/]\" alt=\"[field:title/]\">\r\n      <div class=\"ifsb-show\">[field:title/]</div>\r\n      <div class=\"ifsb-hide\" style=\"top: 351px;\">\r\n        <p>[field:title/]</p>\r\n        <b></b> <span>[field:click/]人已浏览</span> <i>立即查看</i> </div>\r\n      </a>\r\n      </li>\r\n      ",180,835);
$z[1][4]=array();
$z[1][4]['titlelen']="80";
$z[1][4]['orderby']="pubdate";
$z[1][4]['row']="7";

?>