<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006135005.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006135005.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1500";
$z[1][4]['height']="969";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006135011.jpg ",241,388);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006135011.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1500";
$z[2][4]['height']="1125";
$z[3]=Array("img"," /uploads/allimg/171006/1-1G006135013.jpg ",390,537);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171006/1-1G006135013.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="2038";
$z[3][4]['height']="1634";
$z[4]=Array("img"," /uploads/allimg/171006/1-1G006135015.jpg ",539,686);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/171006/1-1G006135015.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="4842";
$z[4][4]['height']="3390";

?>