<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006134A2.jpg ",93,238);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006134A2.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="2040";
$z[1][4]['height']="1534";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006134A3.jpg ",240,385);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006134A3.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="2036";
$z[2][4]['height']="1536";
$z[3]=Array("img"," /uploads/allimg/171006/1-1G006134A5.jpg ",387,532);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171006/1-1G006134A5.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="4842";
$z[3][4]['height']="3390";

?>