<?php
$z[0]=Array("field","",14,42);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",69,95);
$z[1][4]=array();
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",97,126);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("php"," AddFilter(2,1,'fg');",429,471);
$z[3][4]=array();
$z[4]=Array("php"," AddFilter(2,1,'hx');",745,787);
$z[4][4]=array();
$z[5]=Array("php"," AddFilter(2,1,'mj');",1060,1102);
$z[5][4]=array();
$z[6]=Array("field","",1201,1229);
$z[6][4]=array();
$z[6][4]['name']="typeurl";
$z[7]=Array("field","",1247,1273);
$z[7][4]=array();
$z[7][4]['name']="currentstyle";
$z[8]=Array("field","\r\nglobal \$dsql;\r\n\$sql = \"SELECT id From `#@__arctype` WHERE reid='@me' And ishidden<>1 order by sortrank asc limit 0, 100 \";\r\n\$row = \$dsql->GetOne(\$sql);\r\n              @me=is_array(\$row)?'nav-drop':'';\r\n              ",1274,1542);
$z[8][4]=array();
$z[8][4]['name']="typeid";
$z[8][4]['runphp']="yes";
$z[9]=Array("field","",1545,1574);
$z[9][4]=array();
$z[9][4]['name']="typename";
$z[10]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1618,1708);
$z[10][4]=array();
$z[10][4]['type']="son";

?>