{dede:pagestyle maxwidth='800' pagepicnum='3' ddmaxwidth='860' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/181010/1-1Q010161143-lp.jpg' text='客厅' width='1500' height='1125'} /uploads/allimg/181010/1-1Q010161143.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/181010/1-1Q010161203-lp.jpg' text='客厅2' width='1500' height='1125'} /uploads/allimg/181010/1-1Q010161203.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/181010/1-1Q010161220-lp.jpg' text='客厅3' width='1500' height='1125'} /uploads/allimg/181010/1-1Q010161220.jpg {/dede:img}
