{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/171006/1-1G006123H3.jpg' text='' width='1500' height='974'} /uploads/allimg/171006/1-1G006123H3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006123H6.jpg' text='' width='1500' height='1500'} /uploads/allimg/171006/1-1G006123H6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006123H7.jpg' text='' width='1500' height='1500'} /uploads/allimg/171006/1-1G006123H7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006123H9.jpg' text='' width='2970' height='2100'} /uploads/allimg/171006/1-1G006123H9.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006123I1.jpg' text='' width='2970' height='2100'} /uploads/allimg/171006/1-1G006123I1.jpg {/dede:img}
