<?php
$z[0]=Array("id"," \$id=@me;@me='';\$url=GetOneArchive(\$id);@me=\$url['arcurl'];",46,139);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",165,180);
$z[1][4]=array();
$z[2]=Array("title","",212,226);
$z[2][4]=array();
$z[3]=Array("id"," \$id=@me;@me='';\$url=GetOneArchive(\$id);@me=\$url['arcurl'];",319,412);
$z[3][4]=array();
$z[3][4]['runphp']="yes";
$z[4]=Array("title","",414,428);
$z[4][4]=array();

?>