{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061J608.jpg' text='' width='1500' height='1131'} /uploads/allimg/171006/1-1G0061J608.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061J609.jpg' text='' width='1500' height='1131'} /uploads/allimg/171006/1-1G0061J609.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061J610.jpg' text='' width='1500' height='1367'} /uploads/allimg/171006/1-1G0061J610.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061J612.jpg' text='' width='1500' height='1374'} /uploads/allimg/171006/1-1G0061J612.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061J613.jpg' text='' width='1500' height='1368'} /uploads/allimg/171006/1-1G0061J613.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061J614.jpg' text='' width='1500' height='1370'} /uploads/allimg/171006/1-1G0061J614.jpg {/dede:img}
