{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061F512.jpg' text='' width='1500' height='1029'} /uploads/allimg/171006/1-1G0061F512.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061F530.jpg' text='' width='1500' height='1084'} /uploads/allimg/171006/1-1G0061F530.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061F532.jpg' text='' width='1500' height='1074'} /uploads/allimg/171006/1-1G0061F532.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061F533.jpg' text='' width='1500' height='937'} /uploads/allimg/171006/1-1G0061F533.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061F539.jpg' text='' width='1600' height='1280'} /uploads/allimg/171006/1-1G0061F539.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G0061F540.jpg' text='' width='1600' height='1280'} /uploads/allimg/171006/1-1G0061F540.jpg {/dede:img}
