
<field:ch itemname="您的称呼" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ch>

<field:hm itemname="手机号码" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:hm>

<field:mc itemname="小区名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mc>

<field:mj itemname="面积/㎡" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mj>

<field:fg itemname="风格" autofield="1" type="select" isnull="true" default="现代简约,欧美风格,田园风格,地中海风格,中式风格,其他风格"  maxlength="250" page="">
</field:fg>



