<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="860";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/181010/1-1Q010144328.gif ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/181010/1-1Q010144328.gif";
$z[1][4]['text']="1";
$z[1][4]['width']="100";
$z[1][4]['height']="100";
$z[2]=Array("img"," /uploads/allimg/181010/1-1Q010144328-50.gif ",241,393);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/181010/1-1Q010144328-50.gif";
$z[2][4]['text']="2";
$z[2][4]['width']="100";
$z[2][4]['height']="100";
$z[3]=Array("img"," /uploads/allimg/181010/1-1Q010144328-51.gif ",395,547);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/181010/1-1Q010144328-51.gif";
$z[3][4]['text']="3";
$z[3][4]['width']="100";
$z[3][4]['height']="100";
$z[4]=Array("img"," /uploads/allimg/181010/1-1Q010144328-52.gif ",549,701);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/181010/1-1Q010144328-52.gif";
$z[4][4]['text']="3";
$z[4][4]['width']="100";
$z[4][4]['height']="100";

?>