<?php
$z[0]=Array("field","",36,64);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",91,117);
$z[1][4]=array();
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",119,148);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("php"," AddFilter(2,1,'fg');",434,476);
$z[3][4]=array();
$z[4]=Array("php"," AddFilter(2,1,'hx');",751,793);
$z[4][4]=array();
$z[5]=Array("php"," AddFilter(2,1,'mj');",1067,1109);
$z[5][4]=array();

?>