<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="860";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/181010/1-1Q010161143.jpg ",93,246);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/181010/1-1Q010161143.jpg";
$z[1][4]['text']="客厅";
$z[1][4]['width']="1500";
$z[1][4]['height']="1125";
$z[2]=Array("img"," /uploads/allimg/181010/1-1Q010161203.jpg ",248,402);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/181010/1-1Q010161203.jpg";
$z[2][4]['text']="客厅2";
$z[2][4]['width']="1500";
$z[2][4]['height']="1125";
$z[3]=Array("img"," /uploads/allimg/181010/1-1Q010161220.jpg ",404,558);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/181010/1-1Q010161220.jpg";
$z[3][4]['text']="客厅3";
$z[3][4]['width']="1500";
$z[3][4]['height']="1125";

?>