{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/171006/1-1G006132H3.jpg' text='' width='2400' height='1440'} /uploads/allimg/171006/1-1G006132H3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006132I8.jpg' text='' width='2000' height='1500'} /uploads/allimg/171006/1-1G006132I8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/171006/1-1G006132937.jpg' text='' width='3000' height='1500'} /uploads/allimg/171006/1-1G006132937.jpg {/dede:img}
