<div class="team-star team-box fl" style="margin:0;">
            <div class="team-img fl pick-down"> <a href="[field:arcurl/]"> <img src=".[field:picname/]" class="lazy" data-echo="[field:picname/]" width="285" height="350" alt="[field:title/]" /> </a> </div>
            <div class="team-star-info fl">
              <h3>[field:title/]<em>[field:d_zw/]</em></h3>
              <span></span>
              <p>设计理念：[field:description/]</p>
            </div>
          </div>