<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006152Z6.jpg ",93,238);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006152Z6.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1476";
$z[1][4]['height']="1146";
$z[2]=Array("img"," /uploads/allimg/171006/1-1G006152910.jpg ",240,387);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/171006/1-1G006152910.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="2500";
$z[2][4]['height']="1828";
$z[3]=Array("img"," /uploads/allimg/171006/1-1G006152912.jpg ",389,536);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/171006/1-1G006152912.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1600";
$z[3][4]['height']="1280";
$z[4]=Array("img"," /uploads/allimg/171006/1-1G006152913.jpg ",538,685);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/171006/1-1G006152913.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1600";
$z[4][4]['height']="1280";

?>