<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:jz itemname="精装" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="现代简约,低调奢华,尊贵典雅"  maxlength="250" page="">
</field:jz>
<field:mj itemname="装修面积" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="60㎡以下,60-90㎡,90-120㎡,120-150㎡,150㎡以上"  maxlength="250" page="">
</field:mj>
<field:hx itemname="户型" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="一室一厅,两室一厅,三室一厅,四室一厅,其他"  maxlength="250" page="">
</field:hx>
<field:fg itemname="风格" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="北欧,简欧,新中式,美式,现代简约,田园,欧式,中式,混搭"  maxlength="250" page="">
</field:fg>

<field:sjs itemname="设计师ID" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sjs>
<field:zj itemname="造价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="20万"  maxlength="250" page="">
</field:zj>
<field:lpmc itemname="楼盘名称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lpmc>
<field:anmj itemname="案例面积" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="185"  maxlength="250" page="">
</field:anmj>
