<field:house_info itemname="房屋信息" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:house_info>
<field:community itemname="所在小区" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:community>
<field:total_price itemname="总价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:total_price>
<field:c_content itemname="施工内容" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_content>
<field:c_num itemname="施工人数" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="1,2,3,4"  maxlength="250" page="">
</field:c_num>
<field:c_img1 itemname="施工图片1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_img1>
<field:c_img2 itemname="施工图片2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_img2>
<field:c_img3 itemname="施工图片3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_img3>
<field:c_img4 itemname="施工图片4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_img4>
<field:c_jg itemname="施工监管" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_jg>
<field:c_sjs itemname="设计师" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_sjs>
<field:c_jl itemname="项目经理" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_jl>
<field:c_jimg1 itemname="竣工图片1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_jimg1>
<field:c_jimg2 itemname="竣工图片2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_jimg2>
<field:c_jimg3 itemname="竣工图片3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_jimg3>
<field:c_jimg4 itemname="竣工图片4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:c_jimg4>
<field:c_cd itemname="竣工与否" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="已完工,施工中"  maxlength="250" page="">
</field:c_cd>

