<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="860";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/171006/1-1G006151Q0.jpg ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/171006/1-1G006151Q0-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="487";

?>