<?php
$z[0]=Array("channel","\n     <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a> ",116,228);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['row']="8";
$z[1]=Array("global","",350,376);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",494,516);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",534,558);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",606,632);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",857,883);
$z[5][4]=array();
$z[5][4]['name']="cfg_webname";

?>