<?php
$z[0]=Array("global","",92,114);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("global","",260,286);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","(@me==\"\")? @me=\" class='nav-link  active' \":@me=\"\";",450,551);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\n      <li><a href=\"list.php?tid=[field:id/]\" class=\"nav-link \">[field:typename/]</a><span></span></li>\n      ",587,870);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['row']="8";
$z[3][4]['currentstyle']="<li><a href='list.php?tid=~id~' ~rel~ class='nav-link active'>~typename~</a><span></span> </li>";

?>