<?php
$z[0]=Array("field","",304,323);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",324,350);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",390,419);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",458,516);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",904,939);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\n    <div class=\"team-box fl\">\n      <div class=\"team-img\"> <a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" class=\"lazy\" data-echo=\"[field:picname/]\" width=\"285\" height=\"350\" alt=\"[field:title/]\" /> </a> </div>\n      <div class=\"team-info\"> <b>[field:title/]</b> <em>[field:shorttitle/]</em> </div>\n    </div>\n    ",1156,1500);
$z[5][4]=array();
$z[6]=Array("pagelist","",1585,1641);
$z[6][4]=array();
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1709,1746);
$z[7][4]=array();
$z[7][4]['filename']="footer.htm";

?>