<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/1/3
 * Time: 16:49
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
return array (
    'region_id' =>
        array (
            'field' => 'region_id',
            'label' => 'id',
            'pk' => true,
            'add' => false,
            'edit' => false,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'number',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'region_name' =>
        array (
            'field' => 'region_name',
            'label' => '城市名称',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'text',
            'comment' => '',
            'default' => '',
            'SO' => 'like',
        ),
    'parent_id' =>
        array (
            'field' => 'parent_id',
            'label' => '父类id',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'number',
            'comment' => '',
            'default' => '',
            'SO' => '=',
        ),
    'path_ids' =>
        array (
            'field' => 'path_ids',
            'label' => '所有ids ',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'level' =>
        array (
            'field' => 'level',
            'label' => '级别',
            'pk' => false,
            'add' => true,
            'edit' => false,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '',
            'default' => '',
            'SO' => false,
        ),
    'map_x'=>array(
        'field' => 'map_x',
        'label' => 'map_x',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    )
    ,'map_y'=>array(
        'field' => 'map_y',
        'label' => 'map_y',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'orderby'=>
    array(
        'field' => 'orderby',
        'label' => '排序',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => 50,
        'SO' => false,
    ),'closed'=>array(
        'field' => 'closed',
        'label' => '是否关闭',
        'pk' => false,
        'add' => true,
        'edit' => false,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => 0,
        'SO' => false,
    ),
    'city_code'=>array(
        'field' => 'city_code',
        'label' => '城市邮编',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => 0,
        'SO' => false,
    ),
    'adcode'=>array(
        'field' => 'adcode',
        'label' => 'adcode',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => 0,
        'SO' => false,
    )

);
