<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/22
 * Time: 15:33
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}
return array(
    'group_id'=>array(
        'field' => 'group_id',
        'label' => 'ID',
        'pk' => true,
        'add' => false,
        'edit' => false,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'province_id'=>array(
        'field' => 'province_id',
        'label' => '省id',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'city_id'=>array(
        'field' => 'city_id',
        'label' => '城市id',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'group_name'=>array(
        'field' => 'group_name',
        'label' => '团队名称',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'mobile'=>array(
        'field' => 'mobile',
        'label' => '登录用的手机号码',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'passwd'=>array(
        'field' => 'passwd',
        'label' => '密码',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'addr'=>array(
        'field' => 'addr',
        'label' => '地址',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => false,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'dateline'=>array(
        'field' => 'dateline',
        'label' => 'dateline',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'dateline',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'overtime'=>array(
        'field' => 'overtime',
        'label' => '设置的指派过期时间',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'contact'=>array(
        'field' => 'contact',
        'label' => '配送站长',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'face'=>array(
        'field' => 'face',
        'label' => '配送站头像',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'closed'=>array(
        'field' => 'closed',
        'label' => '关闭标识',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => false,
    )
    ,'lng'=>array(
        'field' => 'lng',
        'label' => '经度',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'lat'=>array(
        'field' => 'lat',
        'label' => '纬度',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => false,
        'list' => true,
        'type' => 'text',
        'comment' => '',
        'default' => '',
        'SO' => false,
    ),
    'polygon_point' => 
      array (
        'field' => 'area_polygon',
        'label' => '配送团队区域模板坐标序列化',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => true,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '配送团队区域模板坐标序列化',
        'default' => '',
        'SO' => 'false',
      ),
    'min_amount'=>array(
        'field' => 'min_amount',
        'label' => '配送站起送价',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => true,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'number',
        'comment' => '配送站起送价',
        'default' => '',
        'SO' => 'false',
    ),
    'voice'=>array(
        'field' => 'voice',
        'label' => '语音开关',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => true,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'assign'=>array(
        'field' => 'assign',
        'label' => '指派模式',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => true,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',

    ),
    'limit_order'=>array(
        'field' => 'limit_order',
        'label' => '限制接单',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => true,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    ),
    'is_used'=>array(
        'field' => 'is_used',
        'label' => '是否开启限制接单',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => true,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'int',
        'comment' => '',
        'default' => '',
        'SO' => '',
    )

);