<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/26
 * Time: 16:12
 */
if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
    'complaint_id' =>
        array (
            'field' => 'complaint_id',
            'label' => '评价ID',
            'pk' => true,
            'add' => false,
            'edit' => false,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '评价ID',
            'default' => '',
            'SO' => '=',
        ),
    'shop_id' =>
        array (
            'field' => 'shop_id',
            'label' => '商户ID',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '商户ID',
            'default' => '',
            'SO' => '=',
        ),
    'uid' =>
        array (
            'field' => 'uid',
            'label' => '会员UID',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '会员UID',
            'default' => '',
            'SO' => '=',
        ),
    'order_id' =>
        array (
            'field' => 'order_id',
            'label' => '订单ID',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '订单ID',
            'default' => '',
            'SO' => '=',
        ),
    'staff_id' =>
        array (
            'field' => 'staff_id',
            'label' => '配送员id',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '配送员id',
            'default' => '',
            'SO' => false,
        ),
    'title' =>
        array (
            'field' => 'title',
            'label' => '主题',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'text',
            'comment' => '主题',
            'default' => '',
            'SO' => false,
        ),
    'content' =>
        array (
            'field' => 'content',
            'label' => '评价内容',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'text',
            'comment' => '评价内容',
            'default' => '',
            'SO' => false,
        ),
    'pei_time' =>
        array (
            'field' => 'pei_time',
            'label' => '平均等待时间',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'int',
            'comment' => '平均等待时间',
            'default' => '30',
            'SO' => false,
        ),
    'have_photo' =>
        array (
            'field' => 'have_photo',
            'label' => '是否有图',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'photo',
            'comment' => '是否有截图',
            'default' => '',
            'SO' => false,
        ),
    'reply' =>
        array (
            'field' => 'reply',
            'label' => '回复人',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'text',
            'comment' => '回复人',
            'default' => '',
            'SO' => 'like',
        ),
    'reply_time' =>
        array (
            'field' => 'reply_time',
            'label' => '回复时间',
            'pk' => false,
            'add' => true,
            'edit' => true,
            'html' => false,
            'empty' => true,
            'show' => true,
            'list' => true,
            'type' => 'unixtime',
            'comment' => '回复时间',
            'default' => '',
            'SO' => 'betweendate',
        ),

    'clientip' =>
        array (
            'field' => 'clientip',
            'label' => '客户ip',
            'pk' => false,
            'add' => false,
            'edit' => false,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'clientip',
            'comment' => '客户IP',
            'default' => '',
            'SO' => false,
        ),
    'dateline' =>
        array (
            'field' => 'dateline',
            'label' => '创建时间',
            'pk' => false,
            'add' => false,
            'edit' => false,
            'html' => false,
            'empty' => false,
            'show' => true,
            'list' => true,
            'type' => 'dateline',
            'comment' => '创建时间',
            'default' => '',
            'SO' => 'betweendate',
        ),
);