<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

return array (
  'pid' => 
  array (
    'field' => 'pid',
    'label' => 'PID',
    'pk' => true,
    'add' => false,
    'edit' => false,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => 'pid',
    'default' => '',
    'SO' => '=',
  ),
  'order_id' => 
  array (
    'field' => 'order_id',
    'label' => '订单ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '订单ID',
    'default' => '',
    'SO' => '=',
  ),
  'product_id' => 
  array (
    'field' => 'product_id',
    'label' => '商品ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商品ID',
    'default' => '',
    'SO' => '=',
  ),
  'product_name' => 
  array (
    'field' => 'product_name',
    'label' => '商品名称',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'text',
    'comment' => '商品名称',
    'default' => '',
    'SO' => 'like',
  ),
  'product_price' => 
  array (
    'field' => 'product_price',
    'label' => '商品价格',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '商品价格',
    'default' => '',
    'SO' => 'between',
  ),
  'package_price' => 
  array (
    'field' => 'package_price',
    'label' => '打包费',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '打包费, 0:免打包费',
    'default' => '0.00',
    'SO' => 'between',
  ),
  'product_number' => 
  array (
    'field' => 'product_number',
    'label' => '商品数量',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商品数量',
    'default' => '',
    'SO' => false,
  ),
  'amount' => 
  array (
    'field' => 'amount',
    'label' => '最终要支付金额',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'number',
    'comment' => '最终要支付金额',
    'default' => '0.00',
    'SO' => 'between',
  ),
  'spec_id' => 
  array (
    'field' => 'spec_id',
    'label' => '商品规格ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => false,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '商品规格ID',
    'default' => '',
    'SO' => '=',
  ),
    'unit'=>array(
        'field' => 'unit',
        'label' => '商品单位',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'varchar',
        'comment' => '商品单位',
        'default' => '',
        'SO' => '',
    ),
    'specification'=>array(
        'field' => 'specification',
        'label' => '商品属性',
        'pk' => false,
        'add' => true,
        'edit' => true,
        'html' => false,
        'empty' => true,
        'show' => true,
        'list' => true,
        'type' => 'text',
        'comment' => '商品属性',
        'default' => '',
        'SO' => '',
    ),
    'huodong_id' => 
  array (
    'field' => 'huodong_id',
    'label' => '折扣活动ID',
    'pk' => false,
    'add' => true,
    'edit' => true,
    'html' => false,
    'empty' => true,
    'show' => true,
    'list' => true,
    'type' => 'int',
    'comment' => '折扣活动ID',
    'default' => '',
    'SO' => '=',
  ),
  'product_prices' =>
    array(
        'field'   => 'product_prices',
        'label'   => '商品结算价',
        'pk'      => false,
        'add'     => true,
        'edit'    => true,
        'html'    => false,
        'empty'   => true,
        'show'    => true,
        'list'    => true,
        'type'    => 'number',
        'comment' => '商品结算价',
        'default' => '0.00',
        'SO'      => false,
    ),
  'product_oldprice' =>
    array(
        'field'   => 'product_oldprice',
        'label'   => '商品原价',
        'pk'      => false,
        'add'     => true,
        'edit'    => true,
        'html'    => false,
        'empty'   => true,
        'show'    => true,
        'list'    => true,
        'type'    => 'number',
        'comment' => '商品原价',
        'default' => '0.00',
        'SO'      => false,
    ),
    'product_oldprices' =>
    array(
        'field'   => 'product_oldprices',
        'label'   => '商品总原价',
        'pk'      => false,
        'add'     => true,
        'edit'    => true,
        'html'    => false,
        'empty'   => true,
        'show'    => true,
        'list'    => true,
        'type'    => 'number',
        'comment' => '商品总原价',
        'default' => '0.00',
        'SO'      => false,
    ),
);