<?php
/**
 * Copy Right IJH.CC
 * Each engineer has a duty to keep the code elegant
 * $Id$
 */

if(!defined('__CORE_DIR')){
    exit("Access Denied");
}

class Ctl_Gallery extends Ctl 
{

    public function icons()
    {
        $data = array(
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_02.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_03.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_04.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_05.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_06.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_07.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_08.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_09.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_10.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_11.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_12.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_13.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_14.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_15.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_16.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_17.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_18.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_19.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_20.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_21.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_22.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_23.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_24.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_25.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_26.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_27.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_28.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_29.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_30.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_31.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_32.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_33.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_34.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_35.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_36.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_37.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_38.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_39.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_40.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_41.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_42.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_43.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_44.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_45.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_46.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_47.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_48.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_49.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_50.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_51.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_52.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_53.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_54.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_55.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_56.png'),
            array('icon'=>'http://img01.jhcms.com/wmdemo/default/icon/icon_57.png'),
        );        
        $this->msgbox->set_data('data', $data);        
        $this->msgbox->json();     
    }

    public function advthemes()
    {
        $data = array(
            '1'=>array(
                'theme_id'=>1,
                'title'=>'默认风格',
                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/theme.png',
                'config'=>array(
                    'module1'=>array(
                        'open'=>1,
                        'class'=>1,
                        'background'=>array(
                            '1'=>'',
                            '2'=>'',
                            '3'=>'',
                            '4'=>''
                            ),
                        'background_color'=>'FFFFFF',
                        'color'=>'666666',
                        'icon_location'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_lat_1.png',
                        'icon_down'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_down_1.png',
                        'searchBox'=>array(
                            'open'=>1,
                            'color'=>'666666',
                            'keywords'=>array('脆皮鸡', '排骨饭', '寿司', '凉皮', '老乡鸡', '汉堡')
                            )
                        ),
                    'module2'=>array(
                        'open'=>1,
                        'class'=>1,
                        'background'=>'',
                        'link'=>'',
                        'wxlink'=>'',
                        'content'=>array(
                            array(
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act_ban.png',
                                'link'=>'',
                                'wxlink'=>''
                                )
                            )
                        ),
                    'module3'=>array(
                        'open'=>1,
                        'class'=>1,
                        'background'=>'',
                        'content'=>array(
                            array(
                                'title'=>'分类1',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_1.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类2',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_2.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类3',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_3.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类4',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_4.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类5',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_5.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类6',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_6.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类7',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_7.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类8',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_8.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类9',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_9.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            array(
                                'title'=>'分类10',
                                'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_cla_10.png',
                                'link'=>'',
                                'wxlink'=>''
                                ),
                            )
                        ),
                    'module4'=>array(
                        'open'=>1
                        ),
                    'module5'=>array(
                        'open'=>1,
                        'class'=>1,
                        'title'=>'优惠专区',
                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act_name1.png',
                        'link'=>'',
                        'wxlink'=>'',
                        'content'=>array(
                            '1'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act1_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act1_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act1_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '2'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act2_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act2_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '3'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act3_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '4'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act4_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act4_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act4_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '5'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_4.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '6'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_4.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '7'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_4.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_5.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_6.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            )
                        ),
                    'module6'=>array(
                        'open'=>0,
                        'class'=>1,
                        'title'=>'优惠专区二',
                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act_name1.png',
                        'link'=>'',
                        'wxlink'=>'',
                        'content'=>array(
                            '1'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act1_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act1_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act1_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '2'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act2_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act2_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '3'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act3_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '4'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act4_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act4_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act4_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '5'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act5_4.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '6'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act6_4.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            '7'=>array(
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_1.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_2.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_3.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_4.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_5.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act7_6.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                    ),
                            )

                        ),
                    'module7'=>array(
                        'open'=>1,
                        'class'=>1,
                        'title'=>'大牌甄选',
                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act_name2.png',
                        'link'=>'',
                        'wxlink'=>'',
                        'content'=>array(
                            '1'=>array(
                                    array(
                                        'title'=>'必胜客',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act9_1.png',
                                        //'logo'=>'',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'吉祥混沌',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act9_2.png',
                                        //'logo'=>'',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'青年餐厅',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act9_3.png',
                                        //'logo'=>'',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'老乡鸡',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act9_4.png',
                                        //'logo'=>'',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'台资味',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act9_5.png',
                                        'logo'=>'',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'大脸鸡排',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act9_6.png',
                                        //'logo'=>'',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                ),
                            '2'=>array(
                                    array(
                                        'title'=>'必胜客',
                                        //'logo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act10_5.png',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/pic_shop01@2x.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'吉祥混沌',
                                        //'logo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act10_6.png',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/pic_shop02@2x.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'青年餐厅',
                                        //'logo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act10_7.png',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/pic_shop03@2x.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        ),
                                    array(
                                        'title'=>'台资味',
                                        //'logo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act10_8.png',
                                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/pic_shop04@2x.png',
                                        'link'=>'',
                                        'wxlink'=>''
                                        )
                                )                    
                            )
                        ),
                    'module8'=>array(
                        'open'=>1,
                        'photo'=>'http://img01.jhcms.com/wmdemo/default/image/img_act8.png',
                        'link'=>'',
                        'wxlink'=>''
                        ),
                    'module9'=>array(
                        'open'=>1,
                        'show_huodong'=>1
                        ),
                    'module10'=>array(
                        'open'=>1,
                        'color_checked'=>'20AD20',
                        'color_nochecked'=>'999999',
                        'content'=>array(
                            array(
                                'open'=>1,
                                'title'=>'首页',
                                'link'=>'',
                                'icon_checked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot1_2.png',
                                'icon_nochecked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot1_1.png'                       
                                ),
                            array(
                                'open'=>0,
                                'title'=>'购物车',
                                'link'=>'',
                                'icon_checked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot2_2.png',
                                'icon_nochecked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot2_1.png'
                                ),
                            array(
                                'open'=>1,
                                'title'=>'订单',
                                'link'=>'',
                                'icon_checked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot3_2.png',
                                'icon_nochecked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot3_1.png'
                                ),
                            array(
                                'open'=>1,
                                'title'=>'我的',
                                'link'=>'',
                                'icon_checked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot4_2.png',
                                'icon_nochecked'=>'http://img01.jhcms.com/wmdemo/default/icon_home/icon_foot4_1.png'
                                )
                            )
                        )
                    )
                ),
            );
        $this->msgbox->set_data('data', $data);        
        $this->msgbox->json();
    }

}